web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.dev'
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  env_file:
    - '.env.dev'
  volumes:
    - ./database:/var/lib/mysql:rw
    - ./startdb_docker.sh:/startdb_docker.sh
  command: /startdb_docker.sh
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  env_file:
    - '.env.dev'
# elasticsearch:
#   build: .
#   working_dir: /myapp
#   command: /etc/init -Des.config=/myapp/config/elasticsearch.yml
#   volumes:
#     - /var/lib/docker/groupmates/elasticsearch/data:/data
#     - ./elasticsearch/config:/data/config
#   ports:
#     - "9200:9200"
#     - "9300:9300"
